version: '3.8'

services:
  postgres_db:
    image: postgres:latest
    container_name: PostgresCont 
    restart: always
    environment:
      - POSTGRES_USER=demid
      - POSTGRES_PASSWORD=demid123
    ports:
      - '5432:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data
volumes:
  postgres-data:
    driver: local