FROM apache/airflow:2.4.3
RUN pip install airflow-providers-clickhouse
RUN pip install clickhouse-connect
RUN pip install pandas 
RUN pip install sqlalchemy
RUN pip install gspread==5.7.2
RUN pip install loguru==0.7.2
RUN pip install pytelegrambotapi==4.14.0